# Generated by Django 5.1 on 2024-10-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='lot_size',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Condo', 'Condo'), ('Apartment', 'Apartment'), ('Land', 'Land')], default='House', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='square_footage',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(default=2000),
        ),
    ]
